name: CI Pipeline
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@v6
      with:
        enable-cache: true

    - name: Install dependencies
      run: uv run invoke manage-dependency

    - name: Lint and format with ruff
      run: uv run invoke lint-and-format-code

    - name: Run type checks with mypy
      run: uv run invoke type-hints-check

    - name: Run tests
      run: uv run invoke test-code
